Traceback (most recent call last):
  File "C:\Users\10756\Documents\pythonProject\except\two.py", line 4, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
